<?php

namespace ReadBundle\Repository;

use ReadBundle\Entity\Secao;

/**
 * SecaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecaoRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Secao $secao)
    {
        $this->getEntityManager()->persist($secao);
        $this->getEntityManager()->flush($secao);
    }
}
